# ===== LOCAL PROFILE =====

spring:
  # Postgres
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/epigraph}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # Liquibase
  liquibase:
    change-log: classpath:db/db-changelog.yaml

  # JPA: allow Hibernate to auto-update schema in local dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Google OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

# Jwt Service
app:
  jwt:
    secret: dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3ItZXBpZ3JhcGgtYXBw

# Logging: verbose for local development
logging:
  level:
    root: INFO
    com.mkrasikoff.epigraph: DEBUG
    org.springframework.web: DEBUG
    liquibase: INFO
